import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const HomePage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hola mundo</h1>
      </main>

      <footer className={styles.footer}>
        <p className={styles.footer__text}>Copyright &copy; | x Team 2022</p>
      </footer>
    </div>
  )
}

export default HomePage